---
- name: Windows Variables Load
  ansible.builtin.include_vars:
    file: ../../../variables/os_var/windows_var.yml
    
- name: Domain Administrator Account Configuration
  microsoft.ad.user:
    name: "{{ item.name }}"
    identity: "{{ item.upn | default(omit) }}"
    display_name: "{{ item.display_name | default(omit) }}"
    upn: "{{ item.upn | default(omit) }}"
    email: "{{ item.email | default(omit) }}"
    path: "{{ item.path | default('OU=Administrators,OU=Accounts,DC=khangvum,DC=lab') }}"
    password: "{{ item.password }}"
    update_password: when_changed
    password_never_expires: "{{ item.password_never_expires }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
    groups:
      add:
        - "{{ item.group }}"
    description: "{{ item.description | default(omit) }}"
  loop: "{{ domain_admin_account_list }}"

- name: Domain User Account Configuration
  microsoft.ad.user:
    name: "{{ item.name }}"
    identity: "{{ item.upn }}"
    firstname: "{{ item.firstname | default(omit) }}"
    surname: "{{ item.surname | default(omit) }}"
    display_name: "{{ item.display_name | default(omit) }}"
    sam_account_name: "{{ item.sam_account_name }}"
    upn: "{{ item.upn }}"
    email: "{{ item.email }}"
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
    groups:
      add:
        - "Domain Users"
    password: "{{ item.password }}"
    update_password: on_create
    password_never_expires: "{{ item.password_never_expires }}"
    user_cannot_change_password: false
    description: "{{ item.description | default(omit) }}"
    # Built-in attributes
    street: "{{ item.street | default(omit) }}"
    city: "{{ item.city | default(omit) }}"
    state_province: "{{ item.state_province | default(omit) }}"
    postal_code: "{{ item.postal_code | default(omit) }}"
    country: "{{ item.country | default(omit) }}"
    # Custom attributes
    attributes: "{{ item.attributes | default(omit) }}"
  loop: "{{ domain_user_account_list }}"