---
# Domain administrator configuration
domain_admin_account_list:
  - name: Administrator
    path: "CN=Users,DC=khangvum,DC=lab"
    password: {{ PASSWORD }}
    password_never_expires: true
    state: present
    enabled: true
    group: Domain Admins
  - name: SAD Khang
    display_name: SAD Khang
    upn: SAD_Khang@khangvum.lab
    email: SAD_Khang@khangvum.lab
    path: "OU=Administrators,OU=Accounts,DC=khangvum,DC=lab"
    password: {{ PASSWORD }}
    password_never_expires: true
    state: present
    enabled: true
    group: Domain Admins
    description: Khang Vu's system administrator account

# Domain user accounts
# - Country code: https://www.worlddata.info/countrycodes.php
domain_user_account_list:
  - name: Khang Vu
    firstname: Khang
    surname: Vu
    display_name: Khang Vu
    sam_account_name: kvu
    upn: kvu@khangvum.lab
    email: kvu@khangvum.lab
    path: "CN=Users,DC=khangvum,DC=lab"
    password: {{ PASSWORD }}
    password_never_expires: true
    state: present
    enabled: true
    # Built-in attributes
    street: {{ STREET }}
    city: {{ CITY }}
    state_province: {{ STATE_PROVINCE }}
    postal_code: {{ POSTAL_CODE }}
    country: {{ COUNTRY }}
    # Custom attributes
    attributes:
      set:  
        title: {{ TITLE }}
        department: {{ DEPARTMENT }}
        company: {{ COMPANY }}
        manager: {{ MANAGER }}
        physicalDeliveryOfficeName: {{ PHYSICAL_DELIVERY_OFFICE_NAME }}
        telephoneNumber: {{ TELEPHONE_NUMBER }}